In [83]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
import re
from rules import name_rules, geofeat_rules

In [84]:
pd.set_option('mode.chained_assignment', 'warn')

In [85]:
gb = pd.read_table("data/pristine/GB.txt")

In [86]:
gb

,5653,Phrakhtaes,Phrakhtaes.1,Unnamed: 3,34.56717,33.02724,L,LCTY,GB,Unnamed: 9,05,Unnamed: 11,Unnamed: 12,Unnamed: 13,0,Unnamed: 15,32,Asia/Nicosia,2014-09-30
0,5654,Glossa tou Shyllou,Glossa tou Shyllou,NaN,34.57083,33.02917,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,18,Asia/Nicosia,2014-10-01
1,5655,Arkosyia,Arkosyia,NaN,34.57917,33.02500,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,5,Asia/Nicosia,2014-10-01
2,5656,Ammoskatharaes,Ammoskatharaes,NaN,34.56795,33.01775,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,51,Asia/Nicosia,2014-10-01
3,5657,Skaloua Tris Kazoulies,Skaloua Tris Kazoulies,NaN,34.57083,33.01667,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,42,Asia/Nicosia,2014-10-01
4,5659,Shilliostasha,Shilliostasha,NaN,34.57500,33.02083,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,21,Asia/Nicosia,2014-10-01
5,5660,Ammos tou Dhiplarkakou,Ammos tou Dhiplarkakou,NaN,34.58333,33.01667,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,9,Asia/Nicosia,2014-10-01
6,5662,Langouna tou Tarratsou,Langouna tou Tarratsou,NaN,34.58795,33.00711,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,12,Asia/Nicosia,2014-10-01
7,5663,Vounaroudhkia tou Vromonerou,Vounaroudhkia tou Vromonerou,NaN,34.59167,33.00833,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,6,Asia/Nicosia,2014-10-01
8,5664,Vromonero Kannoudhkia,Vromonero Kannoudhkia,NaN,34.59583,33.00417,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,2,Asia/Nicosia,2014-10-01
9,5665,Limnia,Limnia,NaN,34.60417,33.00417,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,1,Asia/Nicosia,2014-10-01
10,5666,Aplostres,Aplostres,NaN,34.60833,33.00417,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,0,Asia/Nicosia,2014-10-01
11,5667,Lamnies,Lamnies,NaN,34.57500,32.99167,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,51,Asia/Nicosia,2014-10-01
12,5668,Monastery of Saint Nicolas of the Cats,Monastery of Saint Nicolas of the Cats,"Agios Nikolaos Monastery,Agios Nikolaos ton Ga...",34.59949,32.98719,S,MSTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,9,Asia/Nicosia,2015-04-07
13,5669,Ais Varas,Ais Varas,NaN,34.60833,32.99583,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,0,Asia/Nicosia,2014-10-01
14,5670,Vatha,Vatha,NaN,34.57653,32.96254,T,HLL,GB,NaN,05,NaN,NaN,NaN,0,NaN,61,Asia/Nicosia,2014-10-01
15,5671,Kavos Ayios Syllas,Kavos Ayios Syllas,"Kavos Agios Syllas,Kavos Ayios Syllas,Kávos Ág...",34.56861,32.96429,T,CAPE,GB,NaN,05,NaN,NaN,NaN,0,NaN,5,Asia/Nicosia,2015-04-07
16,5672,Vounari tou Kambiou,Vounari tou Kambiou,NaN,34.57314,32.95583,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,30,Asia/Nicosia,2014-10-01
17,5673,Katalymata ton Plakoton,Katalymata ton Plakoton,"Katalymata ton Plakoton,Katalýmata ton Plakotó...",34.58333,32.94583,P,PPL,GB,NaN,05,NaN,NaN,NaN,0,NaN,21,Asia/Nicosia,2014-10-01
18,5674,Panayiotis,Panayiotis,NaN,34.58750,32.95000,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,25,Asia/Nicosia,2014-10-01
19,5675,Lakkos tou Savva,Lakkos tou Savva,NaN,34.59583,32.94583,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,12,Asia/Nicosia,2014-10-01
20,5676,Kapsali,Kapsali,NaN,34.59663,32.95076,T,HLL,GB,NaN,05,NaN,NaN,NaN,0,NaN,36,Asia/Nicosia,2014-10-01
21,5677,Ayios Yeoryios,Ayios Yeoryios,"Agios Georgios,Ayios Yeoryios,Ágios Geórgios,Ά...",34.60332,32.93955,S,CH,GB,NaN,05,NaN,NaN,NaN,0,NaN,1,Asia/Nicosia,2015-04-07
22,5678,Ktista,Ktista,"Khtista,Ktista",34.61250,33.00417,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,-1,Asia/Nicosia,2014-10-02
23,5684,Limnes tou Ayiou Yeoryiou,Limnes tou Ayiou Yeoryiou,NaN,34.61250,32.94167,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,0,Asia/Nicosia,1998-12-11
24,5685,Poly Nero,Poly Nero,NaN,34.62083,32.93750,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,3,Asia/Nicosia,1998-12-10
25,5686,Panayia Galousa,Panayia Galousa,"Panagia Galousa,Panagía Galoúsa,Panayia Galous...",34.63862,32.94441,S,CH,GB,NaN,05,NaN,NaN,NaN,0,NaN,8,Asia/Nicosia,2015-04-07
26,5687,Akrotiri Forest,Akrotiri Forest,NaN,34.63046,32.92704,V,FRST,GB,NaN,05,NaN,NaN,NaN,0,NaN,1,Asia/Nicosia,1998-12-11
27,5688,Ayios Dhimitrianos,Ayios Dhimitrianos,"Agios Dimitrianos,Ayios Dhimitrianos,Ágios Dim...",34.64153,32.92110,S,CH,GB,NaN,05,NaN,NaN,NaN,0,NaN,7,Asia/Nicosia,2015-04-07
28,5689,Ayios Theodhoros,Ayios Theodhoros,"Agios Theodoros,Ayios Theodhoros,Ágios Theódor...",34.65000,32.91250,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,21,Asia/Nicosia,2015-04-07
29,5690,Alakati,Alakati,Alakati,34.65365,32.89793,L,LCTY,GB,NaN,05,NaN,NaN,NaN,0,NaN,7,Asia/Nicosia,2014-06-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51687,10377844,Grantham Hall Farm,Grantham Hall Farm,NaN,51.10999,0.39428,S,FRM,GB,NaN,ENG,G5,29UQ,29UQ010,0,NaN,76,Europe/London,2015-07-20
51688,10377845,Little Coldharbour Farm,Little Coldharbour Farm,NaN,51.12215,0.39733,S,FRM,GB,NaN,ENG,G5,29UQ,29UQ010,0,NaN,78,Europe/London,2015-07-20
51689,10377846,Parsonage Wood,Parsonage Wood,NaN,51.11231,0.38907,V,FRST,GB,NaN,ENG,G5,29UQ,29UQ010,0,NaN,76,Europe/London,2015-07-20
51690,10377847,Windmill Cottages,Windmill Cottages,NaN,51.11328,0.39028,S,HSE,GB,NaN,ENG,G5,29UQ,29UQ010,0,NaN,76,Europe/London,2015-07-20
51691,10377848,Windmill Farm,Windmill Farm,NaN,51.11551,0.39023,S,FRM,GB,NaN,ENG,G5,29UQ,29UQ010,0,NaN,76,Europe/London,2015-07-20
51692,10377849,Hale Wood,Hale Wood,NaN,51.12227,0.40242,V,FRST,GB,NaN,ENG,G5,29UQ,29UQ009,0,NaN,76,Europe/London,2015-07-20
51693,10377850,Pulans Wood,Pulans Wood,NaN,51.12033,0.40379,V,FRST,GB,NaN,ENG,G5,29UQ,29UQ009,0,NaN,76,Europe/London,2015-07-20
51694,10377851,Hazel Street,Hazel Street,NaN,51.13019,0.41589,P,PPLX,GB,NaN,ENG,G5,29UQ,29UQ009,0,NaN,73,Europe/London,2015-07-20
51695,10377852,Church View Farm,Church View Farm,NaN,51.11893,0.40534,S,FRM,GB,NaN,ENG,G5,29UQ,29UQ009,0,NaN,76,Europe/London,2015-07-20
51696,10377853,Minepit Wood,Minepit Wood,NaN,51.11718,0.40521,V,FRST,GB,NaN,ENG,G5,29UQ,29UQ009,0,NaN,76,Europe/London,2015-07-20
51697,10377854,Kettles Shaw,Kettles Shaw,NaN,51.11631,0.41036,V,TREE,GB,NaN,ENG,G5,29UQ,29UQ009,0,NaN,69,Europe/London,2015-07-20
51698,10377855,Pittsgate Farm,Pittsgate Farm,NaN,51.11258,0.40656,S,FRM,GB,NaN,ENG,G5,29UQ,29UQ010,0,NaN,73,Europe/London,2015-07-20
51699,10377856,Pear Tree Cottages,Pear Tree Cottages,NaN,51.11248,0.40343,S,HSE,GB,NaN,ENG,G5,29UQ,29UQ010,0,NaN,73,Europe/London,2015-07-20
51700,10377857,Peak Rock,Peak Rock,NaN,50.33003,-4.51540,T,RK,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,-9999,Europe/London,2015-07-20
51701,10377858,The Warren,The Warren,NaN,50.33237,-4.50806,L,LCTY,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,-9999,Europe/London,2015-07-20
51702,10377859,Southwest Coast Path,Southwest Coast Path,NaN,50.33085,-4.51137,R,TRL,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,-9999,Europe/London,2015-07-20
51703,10377860,High Cove,High Cove,NaN,50.33077,-4.50414,H,COVE,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,-9999,Europe/London,2015-07-20
51704,10377861,Tinkers Cove,Tinkers Cove,NaN,50.33003,-4.51086,H,COVE,GB,NaN,ENG,NaN,NaN,NaN,0,NaN,-9999,Europe/London,2015-07-20
51705,10377862,Polperro Harbor,Polperro Harbor,NaN,50.33118,-4.51654,H,HBR,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,-9999,Europe/London,2015-07-20
51706,10377863,Polperro Harbour Heritage Museum,Polperro Harbour Heritage Museum,NaN,50.33168,-4.51756,S,MUS,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,-9999,Europe/London,2015-07-20
51707,10377864,Chapel Hill,Chapel Hill,NaN,50.33019,-4.51821,T,HLL,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,-9999,Europe/London,2015-07-20
51708,10377865,Chapel Cliff,Chapel Cliff,NaN,50.32961,-4.51845,T,CLF,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,-9999,Europe/London,2015-07-20
51709,10377866,Butts Point,Butts Point,NaN,50.32897,-4.51728,T,PT,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,-9999,Europe/London,2015-07-20
51710,10377867,Kayne Rock,Kayne Rock,NaN,50.32972,-4.52081,T,RK,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,-9999,Europe/London,2015-07-20
51711,10377868,Hard Head,Hard Head,NaN,50.32979,-4.52360,T,HDLD,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,-9999,Europe/London,2015-07-20
51712,10377869,The Coombes,The Coombes,NaN,50.33456,-4.52517,P,PPL,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,39,Europe/London,2015-07-20
51713,10377870,Killigarth,Killigarth,NaN,50.33990,-4.51276,P,PPL,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,45,Europe/London,2015-07-20
51714,10377871,Lamellion,Lamellion,NaN,50.44655,-4.47277,P,PPLX,GB,NaN,ENG,C6,00HE074,NaN,0,NaN,79,Europe/London,2015-07-20
51715,10377872,Oakhanger Stream,Oakhanger Stream,NaN,51.09922,-0.94098,H,STM,GB,NaN,ENG,F2,24UC,24UC031,0,NaN,136,Europe/London,2015-07-20
51716,10377873,The Well Head Stream,The Well Head Stream,NaN,51.09157,-0.93879,H,STM,GB,NaN,ENG,F2,24UC,24UC031,0,NaN,135,Europe/London,2015-07-20

In [ ]:
def setup_gb_dataframe_from_pristine(file_path):
    gb = pd.read_table(file_path)
    column_names = ['geoid', 'name', 'asciiname', 'altname', 'lat', 'long',
        'feature_class', 'feature_code', 'country_code', 'cc2', 'adm1', 'adm2',
        'adm3', 'adm4', 'pop', 'elev', 'delev', 'timezone', 'moddate']
    gb.columns = column_names
    # Removing rows that correspond to Cyprus, N. Ireland, cruft etc.
    remove_these_adm1 = ['05', '00', '01', 'NIR', '03']
    for i in remove_these_adm1:
        gb = gb[gb.adm1 != i]
    # Setting a list of alternate names from altname string field
    gb['ls_altname'] = gb['altname'].dropna().apply(lambda x: x.split(','))
    # Pick only feature codes that correspond to towns and cities, see
    # http://www.geonames.org/export/codes.html
    gb = gb[gb.feature_code.isin(geofeat_rules)]
    return gb

In [ ]:
setup_gb_dataframe_from_pristine("data/pristine/GB.txt")

In [87]:
df = setup_gb_dataframe_from_pristine("data/pristine/GB.txt")

In [88]:
df

,geoid,name,asciiname,altname,lat,long,feature_class,feature_code,country_code,cc2,adm1,adm2,adm3,adm4,pop,elev,delev,timezone,moddate,ls_altname
102,145972,Xylophaghou,Xylophaghou,"Ksilofago,Ksilofagu,Ksilofogo,Xylophaghou,Xylo...",34.97917,33.85000,P,PPL,GB,NaN,NaN,NaN,NaN,NaN,0,NaN,51,Asia/Nicosia,2014-05-29,"[Ksilofago, Ksilofagu, Ksilofogo, Xylophaghou,..."
104,146033,Trachóni,Trachoni,"Kayakale,Trachoni,Trachóni,Trahon,Trahoni,Trak...",34.65756,32.96534,P,PPL,GB,NaN,NaN,NaN,NaN,NaN,0,NaN,30,Asia/Nicosia,2014-03-05,"[Kayakale, Trachoni, Trachóni, Trahon, Trahoni..."
135,2633324,Zennor,Zennor,Zennor,50.19057,-5.56614,P,PPL,GB,NaN,ENG,C6,00HE213,NaN,0,NaN,109,Europe/London,2011-03-03,[Zennor]
136,2633325,Zelah,Zelah,NaN,50.32332,-5.07897,P,PPL,GB,NaN,ENG,C6,00HE129,NaN,0,NaN,76,Europe/London,2011-03-03,NaN
137,2633326,Zeals,Zeals,"Zeal,Zeals",51.08558,-2.31230,P,PPL,GB,NaN,ENG,P8,00HY259,NaN,0,NaN,145,Europe/London,2011-03-03,"[Zeal, Zeals]"
138,2633327,Zeal Monachorum,Zeal Monachorum,Zeal Monachorum,50.82117,-3.81898,P,PPL,GB,NaN,ENG,D4,18UD,NaN,0,NaN,136,Europe/London,2011-03-03,[Zeal Monachorum]
139,2633328,Ythsie,Ythsie,NaN,57.36667,-2.18333,P,PPL,GB,NaN,SCT,T6,NaN,NaN,0,NaN,49,Europe/London,2004-10-06,NaN
142,2633331,Ystradowen,Ystradowen,Ystradowen,51.49056,-3.42194,P,PPL,GB,NaN,WLS,Z3,NaN,NaN,0,NaN,67,Europe/London,2012-01-17,[Ystradowen]
143,2633332,Ystrad Mynach,Ystrad Mynach,NaN,51.64276,-3.23620,P,PPLA2,GB,NaN,WLS,X4,00PK012,NaN,0,NaN,115,Europe/London,2011-03-03,NaN
144,2633333,Ystrad-Meurig,Ystrad-Meurig,"Ystrad-Meurig,Ystradmeuric",52.28333,-3.91667,P,PPL,GB,GB,WLS,X6,NaN,NaN,0,NaN,210,Europe/London,2013-07-11,"[Ystrad-Meurig, Ystradmeuric]"
145,2633334,Ystradgynlais,Ystradgynlais,"Ystradgunlais,Ystradgynlais",51.76667,-3.76667,P,PPLA3,GB,GB,WLS,Y8,00NN110,NaN,0,NaN,68,Europe/London,2011-07-31,"[Ystradgunlais, Ystradgynlais]"
146,2633335,Ystrad-ffin,Ystrad-ffin,"Capel Ystradffin,Ystrad-ffin",52.10000,-3.76667,P,PPL,GB,GB,WLS,X7,NaN,NaN,0,NaN,399,Europe/London,2013-07-11,"[Capel Ystradffin, Ystrad-ffin]"
147,2633336,Ystradfellte,Ystradfellte,Ystradfellte,51.80897,-3.55299,P,PPL,GB,NaN,WLS,Y8,00NN109,NaN,0,NaN,252,Europe/London,2011-03-03,[Ystradfellte]
148,2633337,Ystalyfera,Ystalyfera,"Ystalfera,Ystalyfera",51.76716,-3.78082,P,PPL,GB,NaN,WLS,Y5,00NZ031,NaN,10218,NaN,74,Europe/London,2011-03-03,"[Ystalfera, Ystalyfera]"
149,2633338,Yspytty-Ystwyth,Yspytty-Ystwyth,NaN,52.33333,-3.86667,P,PPL,GB,NaN,WLS,X6,NaN,NaN,0,NaN,165,Europe/London,2013-07-11,NaN
150,2633339,Ysbyty Ifan,Ysbyty Ifan,"Yspytty Evan,Yspytty-Ifan",53.01667,-3.73333,P,PPL,GB,NaN,WLS,Y2,NaN,NaN,0,NaN,246,Europe/London,2013-12-06,"[Yspytty Evan, Yspytty-Ifan]"
151,2633340,Yspytty Cynfyn,Yspytty Cynfyn,"Yspytty Cyfyn,Yspytty Cynfyn",52.40000,-3.83333,P,PPL,GB,GB,WLS,X6,NaN,NaN,0,NaN,212,Europe/London,2013-07-11,"[Yspytty Cyfyn, Yspytty Cynfyn]"
155,2633344,Yoxford,Yoxford,Yoxford,52.26819,1.50681,P,PPL,GB,NaN,ENG,N5,42UG,NaN,0,NaN,16,Europe/London,2011-03-03,[Yoxford]
156,2633345,Yoxall,Yoxall,Yoxall,52.76659,-1.79068,P,PPL,GB,NaN,ENG,M9,41UC,NaN,0,NaN,66,Europe/London,2011-03-03,[Yoxall]
157,2633346,Youlgreave,Youlgreave,NaN,53.17399,-1.69044,P,PPL,GB,NaN,ENG,D3,17UF,NaN,0,NaN,187,Europe/London,2010-11-07,NaN
158,2633347,Yorton,Yorton,Yorton,52.80921,-2.73854,P,PPL,GB,NaN,ENG,L6,00GG130,NaN,0,NaN,87,Europe/London,2011-03-03,[Yorton]
163,2633352,York,York,"Aebura,Eabhrac,Eabhraig,Eboracum,Efrog,Eoforwi...",53.95763,-1.08271,P,PPLA2,GB,NaN,ENG,Q5,NaN,NaN,144202,NaN,17,Europe/London,2012-03-30,"[Aebura, Eabhrac, Eabhraig, Eboracum, Efrog, E..."
165,2633354,Yokefleet,Yokefleet,NaN,53.70805,-0.75738,P,PPL,GB,NaN,ENG,E1,00FB018,NaN,0,NaN,5,Europe/London,2011-03-03,NaN
166,2633355,Yockleton,Yockleton,Yockleton,52.68547,-2.88917,P,PPL,GB,NaN,ENG,L6,00GG187,NaN,0,NaN,98,Europe/London,2011-03-03,[Yockleton]
172,2633363,Yiewsley,Yiewsley,NaN,51.51326,-0.47297,P,PPL,GB,NaN,ENG,GLA,F9,NaN,0,NaN,33,Europe/London,2010-05-24,NaN
175,2633366,Yetminster,Yetminster,Yetminster,50.89579,-2.57959,P,PPL,GB,NaN,ENG,D6,19UH,NaN,0,NaN,62,Europe/London,2011-03-03,[Yetminster]
176,2633367,Yetlington,Yetlington,NaN,55.38190,-1.96856,P,PPL,GB,NaN,ENG,J6,00EM031,NaN,0,NaN,190,Europe/London,2011-03-03,NaN
179,2633370,Yerbeston,Yerbeston,NaN,51.74600,-4.80767,P,PPL,GB,NaN,WLS,Y7,00NS026,NaN,0,NaN,63,Europe/London,2011-03-03,NaN
180,2633371,Yeovilton,Yeovilton,YEO,51.00359,-2.64898,P,PPL,GB,NaN,ENG,M3,40UD,NaN,0,NaN,19,Europe/London,2011-03-03,[YEO]
182,2633373,Yeovil,Yeovil,"Giuela,Jeovil',Jouvil,Jouvilis,Yeovil,yobil,Йе...",50.94159,-2.63211,P,PPL,GB,NaN,ENG,M3,40UD,NaN,43733,NaN,55,Europe/London,2011-03-03,"[Giuela, Jeovil', Jouvil, Jouvilis, Yeovil, yo..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51566,10377357,Upper Ley,Upper Ley,NaN,51.85693,-2.39635,P,PPL,GB,NaN,ENG,E6,23UD,23UD038,0,NaN,45,Europe/London,2015-07-18,NaN
51568,10377359,Grange Court,Grange Court,NaN,51.84797,-2.38841,P,PPL,GB,NaN,ENG,E6,23UD,23UD038,0,NaN,40,Europe/London,2015-07-18,NaN
51569,10377360,Northwood Green,Northwood Green,NaN,51.84445,-2.40918,P,PPL,GB,NaN,ENG,E6,23UD,23UD038,0,NaN,35,Europe/London,2015-07-18,NaN
51570,10377361,Taynton Village,Taynton Village,NaN,51.89395,-2.39549,P,PPL,GB,NaN,ENG,E6,23UD,23UD034,0,NaN,64,Europe/London,2015-07-18,NaN
51571,10377362,Mungoswells,Mungoswells,NaN,56.00088,-2.81108,P,PPL,GB,NaN,SCT,U6,NaN,NaN,0,NaN,34,Europe/London,2015-07-18,NaN
51572,10377363,Ballencrieff,Ballencrieff,NaN,55.99310,-2.82919,P,PPL,GB,NaN,SCT,U6,NaN,NaN,0,NaN,49,Europe/London,2015-07-18,NaN
51573,10377364,Spittal,Spittal,NaN,55.98468,-2.86786,P,PPL,GB,NaN,SCT,U6,NaN,NaN,0,NaN,38,Europe/London,2015-07-18,NaN
51576,10377368,Grasholme,Grasholme,NaN,54.58999,-2.11834,P,PPL,GB,NaN,ENG,D8,00EJ071,NaN,0,NaN,301,Europe/London,2015-07-19,NaN
51579,10377371,Edburton,Edburton,NaN,50.89047,-0.25466,P,PPL,GB,NaN,ENG,P6,45UF,45UF027,0,NaN,127,Europe/London,2015-07-19,NaN
51589,10377694,Soar,Soar,NaN,53.22302,-4.42011,P,PPL,GB,NaN,WLS,X1,00NA001,NaN,0,NaN,20,Europe/London,2015-07-19,NaN
51591,10377699,Bethel,Bethel,NaN,53.20781,-4.40406,P,PPL,GB,NaN,WLS,X1,00NA006,NaN,0,NaN,6,Europe/London,2015-07-19,NaN
51592,10377701,Trefdraeth,Trefdraeth,NaN,53.20542,-4.38951,P,PPL,GB,NaN,WLS,X1,00NA006,NaN,0,NaN,9,Europe/London,2015-07-19,NaN
51593,10377703,Malltraeth,Malltraeth,NaN,53.19243,-4.38509,P,PPL,GB,NaN,WLS,X1,00NA006,NaN,0,NaN,5,Europe/London,2015-07-19,NaN
51594,10377705,Hermon,Hermon,NaN,53.19269,-4.41045,P,PPL,GB,NaN,WLS,X1,00NA006,NaN,0,NaN,1,Europe/London,2015-07-19,NaN
51595,10377710,Paradwys,Paradwys,NaN,53.21200,-4.36505,P,PPL,GB,NaN,WLS,X1,00NA026,NaN,0,NaN,7,Europe/London,2015-07-19,NaN
51596,10377712,Capel Mawr,Capel Mawr,NaN,53.22009,-4.37578,P,PPL,GB,NaN,WLS,X1,00NA026,NaN,0,NaN,19,Europe/London,2015-07-19,NaN
51601,10377724,Broadridge Heath,Broadridge Heath,NaN,51.07223,-0.36019,P,PPL,GB,NaN,ENG,P6,45UF,45UF006,0,NaN,53,Europe/London,2015-07-19,NaN
51602,10377733,Strood Green,Strood Green,NaN,51.08328,-0.37731,P,PPL,GB,NaN,ENG,P6,45UF,45UF028,0,NaN,50,Europe/London,2015-07-19,NaN
51607,10377751,Clemsfold,Clemsfold,NaN,51.08953,-0.39512,P,PPL,GB,NaN,ENG,P6,45UF,45UF021,0,NaN,47,Europe/London,2015-07-19,NaN
51608,10377752,Rowhook,Rowhook,NaN,51.09554,-0.39783,P,PPL,GB,NaN,ENG,P6,45UF,45UF028,0,NaN,49,Europe/London,2015-07-19,NaN
51609,10377753,Ellen's Green,Ellen's Green,NaN,51.10861,-0.43302,P,PPL,GB,NaN,ENG,N7,43UL,43UL009,0,NaN,62,Europe/London,2015-07-19,NaN
51610,10377754,Rudwick,Rudwick,NaN,51.09608,-0.44589,P,PPL,GB,NaN,ENG,P6,45UF,45UF017,0,NaN,43,Europe/London,2015-07-19,NaN
51616,10377760,Hill Wootton,Hill Wootton,NaN,52.31716,-1.55946,P,PPL,GB,NaN,ENG,P3,44UF,44UF019,0,NaN,74,Europe/London,2015-07-19,NaN
51617,10377761,Guys Cliffe,Guys Cliffe,NaN,52.29638,-1.57675,P,PPL,GB,NaN,ENG,P3,44UF,44UF029,0,NaN,74,Europe/London,2015-07-19,NaN
51631,10377783,Ashley,Ashley,NaN,50.89229,-3.49773,P,PPL,GB,NaN,ENG,D4,18UD,18UD052,0,NaN,83,Europe/London,2015-07-19,NaN
51651,10377803,Little London,Little London,NaN,50.95751,0.23299,P,PPL,GB,NaN,ENG,E2,21UH,21UH020,0,NaN,76,Europe/London,2015-07-19,NaN
51657,10377809,Pedlinge,Pedlinge,NaN,51.07878,1.05301,P,PPL,GB,NaN,ENG,G5,NaN,29UL022,0,NaN,59,Europe/London,2015-07-19,NaN
51670,10377822,Abbeymead,Abbeymead,NaN,51.84893,-2.20040,P,PPL,GB,NaN,ENG,E6,23UE,NaN,0,NaN,69,Europe/London,2015-07-19,NaN
51712,10377869,The Coombes,The Coombes,NaN,50.33456,-4.52517,P,PPL,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,39,Europe/London,2015-07-20,NaN
51713,10377870,Killigarth,Killigarth,NaN,50.33990,-4.51276,P,PPL,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,45,Europe/London,2015-07-20,NaN

In [64]:
def setup_name_families(df):
    """In-place setup name families for df dataframe. 
    Note: this only acts on the 'name' field. Use another function to setup
    altname families
    Column changes: will add a ls_namefam column
    TODO: This is a one run deal. Fix.
    """
    df = df.copy()
    df["ls_namefam"] = np.nan
    # Iterate over rows in dataframe
    for index, row in df.iterrows():
        # For each row, check each name_rule
        for namekey, ls_regex in name_rules.iteritems():
            result = patinstr(row.loc['name'], ls_regex)
            if result:
                cur = df.loc[index, 'ls_namefam']
                if not isinstance(cur, list):
                    print df.loc[index, 'name'], namekey
                    df.loc[index, 'name'] = (list([namekey]))
                else:
                    df.loc[index, 'name'].append(namekey)
    return df

In [ ]:
def patinstr(string, patlist):
    """Search string for a substring instance defined by patlist; return
    re.match if found, None if not found"""
    found = None
    for pat in patlist:
        found = re.match(pat, string)
        if found:
            break

    return found

In [ ]:
def patinls(slist, patlist):
    """Search each string in slist for a substring instance defined by patlist;
    return re.match if found, None if not found"""
    found = None
    try:
        strings = iter(slist)
    except TypeError:
        return
    for string in strings:
        if not found:
            for pat in patlist:
                found = re.match(pat, string)
                if found:
                    break
        else:
            break
    return found

In [89]:
df = df.copy()

In [95]:
df_alt = DataFrame()

In [101]:
for index, row in df.iterrows():
    df_alt.append(row[:'asciiname'])

In [103]:
def setgb(file_path):
    """Read the GB.txt file from geonames and return an appropriately
    filtered DataFrame"""
    gb = pd.read_table(file_path)
    column_names = ['geoid', 'name', 'asciiname', 'altname', 'lat', 'long',
        'feature_class', 'feature_code', 'country_code', 'cc2', 'adm1', 'adm2',
        'adm3', 'adm4', 'pop', 'elev', 'delev', 'timezone', 'moddate']
    gb.columns = column_names
    # Removing rows that correspond to Cyprus, N. Ireland, cruft etc.
    remove_these_adm1 = ['05', '00', '01', 'NIR', '03']
    for i in remove_these_adm1:
        gb = gb[gb.adm1 != i]
    # Setting a list of alternate names from altname string field
    gb['ls_altname'] = gb['altname'].dropna().apply(lambda x: x.split(','))
    # Pick only feature codes that correspond to towns and cities, see
    # http://www.geonames.org/export/codes.html
    gb = gb[gb.feature_code.isin(geofeat_rules)]
    gb.index = range(len(gb))
    return gb

In [106]:
gb = setgb("data/pristine/GB.txt")

In [105]:
def setfam(dfin):
    """In-place setup name families for df dataframe.

    Note: this only acts on the 'name' field. Use another function to setup
    altname families

    Column changes: will add a ls_namefam column

    TODO: This is a one run deal; not idempotent. Fix.
    """
    df = dfin.copy()
    df["ls_namefam"] = np.nan
    # Iterate over rows in dataframe
    for index, row in df.iterrows():
        # For each row, check each name_rule
        for namekey, ls_regex in name_rules.iteritems():
            result = patinstr(row.loc['name'], ls_regex)
            if result:
                cur = df.loc[index, 'ls_namefam']
                if not isinstance(cur, list):
                    df.loc[index, 'ls_namefam'] = list([namekey])
                else:
                    df.loc[index, 'ls_namefam'].append(namekey)
    return df

    # list([name]) if no

In [108]:
gb

,geoid,name,asciiname,altname,lat,long,feature_class,feature_code,country_code,cc2,adm1,adm2,adm3,adm4,pop,elev,delev,timezone,moddate,ls_altname
0,145972,Xylophaghou,Xylophaghou,"Ksilofago,Ksilofagu,Ksilofogo,Xylophaghou,Xylo...",34.97917,33.85000,P,PPL,GB,NaN,NaN,NaN,NaN,NaN,0,NaN,51,Asia/Nicosia,2014-05-29,"[Ksilofago, Ksilofagu, Ksilofogo, Xylophaghou,..."
1,146033,Trachóni,Trachoni,"Kayakale,Trachoni,Trachóni,Trahon,Trahoni,Trak...",34.65756,32.96534,P,PPL,GB,NaN,NaN,NaN,NaN,NaN,0,NaN,30,Asia/Nicosia,2014-03-05,"[Kayakale, Trachoni, Trachóni, Trahon, Trahoni..."
2,2633324,Zennor,Zennor,Zennor,50.19057,-5.56614,P,PPL,GB,NaN,ENG,C6,00HE213,NaN,0,NaN,109,Europe/London,2011-03-03,[Zennor]
3,2633325,Zelah,Zelah,NaN,50.32332,-5.07897,P,PPL,GB,NaN,ENG,C6,00HE129,NaN,0,NaN,76,Europe/London,2011-03-03,NaN
4,2633326,Zeals,Zeals,"Zeal,Zeals",51.08558,-2.31230,P,PPL,GB,NaN,ENG,P8,00HY259,NaN,0,NaN,145,Europe/London,2011-03-03,"[Zeal, Zeals]"
5,2633327,Zeal Monachorum,Zeal Monachorum,Zeal Monachorum,50.82117,-3.81898,P,PPL,GB,NaN,ENG,D4,18UD,NaN,0,NaN,136,Europe/London,2011-03-03,[Zeal Monachorum]
6,2633328,Ythsie,Ythsie,NaN,57.36667,-2.18333,P,PPL,GB,NaN,SCT,T6,NaN,NaN,0,NaN,49,Europe/London,2004-10-06,NaN
7,2633331,Ystradowen,Ystradowen,Ystradowen,51.49056,-3.42194,P,PPL,GB,NaN,WLS,Z3,NaN,NaN,0,NaN,67,Europe/London,2012-01-17,[Ystradowen]
8,2633332,Ystrad Mynach,Ystrad Mynach,NaN,51.64276,-3.23620,P,PPLA2,GB,NaN,WLS,X4,00PK012,NaN,0,NaN,115,Europe/London,2011-03-03,NaN
9,2633333,Ystrad-Meurig,Ystrad-Meurig,"Ystrad-Meurig,Ystradmeuric",52.28333,-3.91667,P,PPL,GB,GB,WLS,X6,NaN,NaN,0,NaN,210,Europe/London,2013-07-11,"[Ystrad-Meurig, Ystradmeuric]"
10,2633334,Ystradgynlais,Ystradgynlais,"Ystradgunlais,Ystradgynlais",51.76667,-3.76667,P,PPLA3,GB,GB,WLS,Y8,00NN110,NaN,0,NaN,68,Europe/London,2011-07-31,"[Ystradgunlais, Ystradgynlais]"
11,2633335,Ystrad-ffin,Ystrad-ffin,"Capel Ystradffin,Ystrad-ffin",52.10000,-3.76667,P,PPL,GB,GB,WLS,X7,NaN,NaN,0,NaN,399,Europe/London,2013-07-11,"[Capel Ystradffin, Ystrad-ffin]"
12,2633336,Ystradfellte,Ystradfellte,Ystradfellte,51.80897,-3.55299,P,PPL,GB,NaN,WLS,Y8,00NN109,NaN,0,NaN,252,Europe/London,2011-03-03,[Ystradfellte]
13,2633337,Ystalyfera,Ystalyfera,"Ystalfera,Ystalyfera",51.76716,-3.78082,P,PPL,GB,NaN,WLS,Y5,00NZ031,NaN,10218,NaN,74,Europe/London,2011-03-03,"[Ystalfera, Ystalyfera]"
14,2633338,Yspytty-Ystwyth,Yspytty-Ystwyth,NaN,52.33333,-3.86667,P,PPL,GB,NaN,WLS,X6,NaN,NaN,0,NaN,165,Europe/London,2013-07-11,NaN
15,2633339,Ysbyty Ifan,Ysbyty Ifan,"Yspytty Evan,Yspytty-Ifan",53.01667,-3.73333,P,PPL,GB,NaN,WLS,Y2,NaN,NaN,0,NaN,246,Europe/London,2013-12-06,"[Yspytty Evan, Yspytty-Ifan]"
16,2633340,Yspytty Cynfyn,Yspytty Cynfyn,"Yspytty Cyfyn,Yspytty Cynfyn",52.40000,-3.83333,P,PPL,GB,GB,WLS,X6,NaN,NaN,0,NaN,212,Europe/London,2013-07-11,"[Yspytty Cyfyn, Yspytty Cynfyn]"
17,2633344,Yoxford,Yoxford,Yoxford,52.26819,1.50681,P,PPL,GB,NaN,ENG,N5,42UG,NaN,0,NaN,16,Europe/London,2011-03-03,[Yoxford]
18,2633345,Yoxall,Yoxall,Yoxall,52.76659,-1.79068,P,PPL,GB,NaN,ENG,M9,41UC,NaN,0,NaN,66,Europe/London,2011-03-03,[Yoxall]
19,2633346,Youlgreave,Youlgreave,NaN,53.17399,-1.69044,P,PPL,GB,NaN,ENG,D3,17UF,NaN,0,NaN,187,Europe/London,2010-11-07,NaN
20,2633347,Yorton,Yorton,Yorton,52.80921,-2.73854,P,PPL,GB,NaN,ENG,L6,00GG130,NaN,0,NaN,87,Europe/London,2011-03-03,[Yorton]
21,2633352,York,York,"Aebura,Eabhrac,Eabhraig,Eboracum,Efrog,Eoforwi...",53.95763,-1.08271,P,PPLA2,GB,NaN,ENG,Q5,NaN,NaN,144202,NaN,17,Europe/London,2012-03-30,"[Aebura, Eabhrac, Eabhraig, Eboracum, Efrog, E..."
22,2633354,Yokefleet,Yokefleet,NaN,53.70805,-0.75738,P,PPL,GB,NaN,ENG,E1,00FB018,NaN,0,NaN,5,Europe/London,2011-03-03,NaN
23,2633355,Yockleton,Yockleton,Yockleton,52.68547,-2.88917,P,PPL,GB,NaN,ENG,L6,00GG187,NaN,0,NaN,98,Europe/London,2011-03-03,[Yockleton]
24,2633363,Yiewsley,Yiewsley,NaN,51.51326,-0.47297,P,PPL,GB,NaN,ENG,GLA,F9,NaN,0,NaN,33,Europe/London,2010-05-24,NaN
25,2633366,Yetminster,Yetminster,Yetminster,50.89579,-2.57959,P,PPL,GB,NaN,ENG,D6,19UH,NaN,0,NaN,62,Europe/London,2011-03-03,[Yetminster]
26,2633367,Yetlington,Yetlington,NaN,55.38190,-1.96856,P,PPL,GB,NaN,ENG,J6,00EM031,NaN,0,NaN,190,Europe/London,2011-03-03,NaN
27,2633370,Yerbeston,Yerbeston,NaN,51.74600,-4.80767,P,PPL,GB,NaN,WLS,Y7,00NS026,NaN,0,NaN,63,Europe/London,2011-03-03,NaN
28,2633371,Yeovilton,Yeovilton,YEO,51.00359,-2.64898,P,PPL,GB,NaN,ENG,M3,40UD,NaN,0,NaN,19,Europe/London,2011-03-03,[YEO]
29,2633373,Yeovil,Yeovil,"Giuela,Jeovil',Jouvil,Jouvilis,Yeovil,yobil,Йе...",50.94159,-2.63211,P,PPL,GB,NaN,ENG,M3,40UD,NaN,43733,NaN,55,Europe/London,2011-03-03,"[Giuela, Jeovil', Jouvil, Jouvilis, Yeovil, yo..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11572,10377357,Upper Ley,Upper Ley,NaN,51.85693,-2.39635,P,PPL,GB,NaN,ENG,E6,23UD,23UD038,0,NaN,45,Europe/London,2015-07-18,NaN
11573,10377359,Grange Court,Grange Court,NaN,51.84797,-2.38841,P,PPL,GB,NaN,ENG,E6,23UD,23UD038,0,NaN,40,Europe/London,2015-07-18,NaN
11574,10377360,Northwood Green,Northwood Green,NaN,51.84445,-2.40918,P,PPL,GB,NaN,ENG,E6,23UD,23UD038,0,NaN,35,Europe/London,2015-07-18,NaN
11575,10377361,Taynton Village,Taynton Village,NaN,51.89395,-2.39549,P,PPL,GB,NaN,ENG,E6,23UD,23UD034,0,NaN,64,Europe/London,2015-07-18,NaN
11576,10377362,Mungoswells,Mungoswells,NaN,56.00088,-2.81108,P,PPL,GB,NaN,SCT,U6,NaN,NaN,0,NaN,34,Europe/London,2015-07-18,NaN
11577,10377363,Ballencrieff,Ballencrieff,NaN,55.99310,-2.82919,P,PPL,GB,NaN,SCT,U6,NaN,NaN,0,NaN,49,Europe/London,2015-07-18,NaN
11578,10377364,Spittal,Spittal,NaN,55.98468,-2.86786,P,PPL,GB,NaN,SCT,U6,NaN,NaN,0,NaN,38,Europe/London,2015-07-18,NaN
11579,10377368,Grasholme,Grasholme,NaN,54.58999,-2.11834,P,PPL,GB,NaN,ENG,D8,00EJ071,NaN,0,NaN,301,Europe/London,2015-07-19,NaN
11580,10377371,Edburton,Edburton,NaN,50.89047,-0.25466,P,PPL,GB,NaN,ENG,P6,45UF,45UF027,0,NaN,127,Europe/London,2015-07-19,NaN
11581,10377694,Soar,Soar,NaN,53.22302,-4.42011,P,PPL,GB,NaN,WLS,X1,00NA001,NaN,0,NaN,20,Europe/London,2015-07-19,NaN
11582,10377699,Bethel,Bethel,NaN,53.20781,-4.40406,P,PPL,GB,NaN,WLS,X1,00NA006,NaN,0,NaN,6,Europe/London,2015-07-19,NaN
11583,10377701,Trefdraeth,Trefdraeth,NaN,53.20542,-4.38951,P,PPL,GB,NaN,WLS,X1,00NA006,NaN,0,NaN,9,Europe/London,2015-07-19,NaN
11584,10377703,Malltraeth,Malltraeth,NaN,53.19243,-4.38509,P,PPL,GB,NaN,WLS,X1,00NA006,NaN,0,NaN,5,Europe/London,2015-07-19,NaN
11585,10377705,Hermon,Hermon,NaN,53.19269,-4.41045,P,PPL,GB,NaN,WLS,X1,00NA006,NaN,0,NaN,1,Europe/London,2015-07-19,NaN
11586,10377710,Paradwys,Paradwys,NaN,53.21200,-4.36505,P,PPL,GB,NaN,WLS,X1,00NA026,NaN,0,NaN,7,Europe/London,2015-07-19,NaN
11587,10377712,Capel Mawr,Capel Mawr,NaN,53.22009,-4.37578,P,PPL,GB,NaN,WLS,X1,00NA026,NaN,0,NaN,19,Europe/London,2015-07-19,NaN
11588,10377724,Broadridge Heath,Broadridge Heath,NaN,51.07223,-0.36019,P,PPL,GB,NaN,ENG,P6,45UF,45UF006,0,NaN,53,Europe/London,2015-07-19,NaN
11589,10377733,Strood Green,Strood Green,NaN,51.08328,-0.37731,P,PPL,GB,NaN,ENG,P6,45UF,45UF028,0,NaN,50,Europe/London,2015-07-19,NaN
11590,10377751,Clemsfold,Clemsfold,NaN,51.08953,-0.39512,P,PPL,GB,NaN,ENG,P6,45UF,45UF021,0,NaN,47,Europe/London,2015-07-19,NaN
11591,10377752,Rowhook,Rowhook,NaN,51.09554,-0.39783,P,PPL,GB,NaN,ENG,P6,45UF,45UF028,0,NaN,49,Europe/London,2015-07-19,NaN
11592,10377753,Ellen's Green,Ellen's Green,NaN,51.10861,-0.43302,P,PPL,GB,NaN,ENG,N7,43UL,43UL009,0,NaN,62,Europe/London,2015-07-19,NaN
11593,10377754,Rudwick,Rudwick,NaN,51.09608,-0.44589,P,PPL,GB,NaN,ENG,P6,45UF,45UF017,0,NaN,43,Europe/London,2015-07-19,NaN
11594,10377760,Hill Wootton,Hill Wootton,NaN,52.31716,-1.55946,P,PPL,GB,NaN,ENG,P3,44UF,44UF019,0,NaN,74,Europe/London,2015-07-19,NaN
11595,10377761,Guys Cliffe,Guys Cliffe,NaN,52.29638,-1.57675,P,PPL,GB,NaN,ENG,P3,44UF,44UF029,0,NaN,74,Europe/London,2015-07-19,NaN
11596,10377783,Ashley,Ashley,NaN,50.89229,-3.49773,P,PPL,GB,NaN,ENG,D4,18UD,18UD052,0,NaN,83,Europe/London,2015-07-19,NaN
11597,10377803,Little London,Little London,NaN,50.95751,0.23299,P,PPL,GB,NaN,ENG,E2,21UH,21UH020,0,NaN,76,Europe/London,2015-07-19,NaN
11598,10377809,Pedlinge,Pedlinge,NaN,51.07878,1.05301,P,PPL,GB,NaN,ENG,G5,NaN,29UL022,0,NaN,59,Europe/London,2015-07-19,NaN
11599,10377822,Abbeymead,Abbeymead,NaN,51.84893,-2.20040,P,PPL,GB,NaN,ENG,E6,23UE,NaN,0,NaN,69,Europe/London,2015-07-19,NaN
11600,10377869,The Coombes,The Coombes,NaN,50.33456,-4.52517,P,PPL,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,39,Europe/London,2015-07-20,NaN
11601,10377870,Killigarth,Killigarth,NaN,50.33990,-4.51276,P,PPL,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,45,Europe/London,2015-07-20,NaN

In [110]:
df['parent'] = np.nan

In [112]:
df_alt = DataFrame()

In [113]:
df_alt

Empty DataFrame
Columns: []
Index: []

In [114]:
df_alt = df.copy()

In [117]:
df_alt.drop(['altname'],inplace=True,axis=1)

In [119]:
df_alt.drop(['ls_altname'],inplace=True,axis=1)

In [120]:
df_alt

,geoid,name,asciiname,lat,long,feature_class,feature_code,country_code,cc2,adm1,adm2,adm3,adm4,pop,elev,delev,timezone,moddate,parent
102,145972,Xylophaghou,Xylophaghou,34.97917,33.85000,P,PPL,GB,NaN,NaN,NaN,NaN,NaN,0,NaN,51,Asia/Nicosia,2014-05-29,NaN
104,146033,Trachóni,Trachoni,34.65756,32.96534,P,PPL,GB,NaN,NaN,NaN,NaN,NaN,0,NaN,30,Asia/Nicosia,2014-03-05,NaN
135,2633324,Zennor,Zennor,50.19057,-5.56614,P,PPL,GB,NaN,ENG,C6,00HE213,NaN,0,NaN,109,Europe/London,2011-03-03,NaN
136,2633325,Zelah,Zelah,50.32332,-5.07897,P,PPL,GB,NaN,ENG,C6,00HE129,NaN,0,NaN,76,Europe/London,2011-03-03,NaN
137,2633326,Zeals,Zeals,51.08558,-2.31230,P,PPL,GB,NaN,ENG,P8,00HY259,NaN,0,NaN,145,Europe/London,2011-03-03,NaN
138,2633327,Zeal Monachorum,Zeal Monachorum,50.82117,-3.81898,P,PPL,GB,NaN,ENG,D4,18UD,NaN,0,NaN,136,Europe/London,2011-03-03,NaN
139,2633328,Ythsie,Ythsie,57.36667,-2.18333,P,PPL,GB,NaN,SCT,T6,NaN,NaN,0,NaN,49,Europe/London,2004-10-06,NaN
142,2633331,Ystradowen,Ystradowen,51.49056,-3.42194,P,PPL,GB,NaN,WLS,Z3,NaN,NaN,0,NaN,67,Europe/London,2012-01-17,NaN
143,2633332,Ystrad Mynach,Ystrad Mynach,51.64276,-3.23620,P,PPLA2,GB,NaN,WLS,X4,00PK012,NaN,0,NaN,115,Europe/London,2011-03-03,NaN
144,2633333,Ystrad-Meurig,Ystrad-Meurig,52.28333,-3.91667,P,PPL,GB,GB,WLS,X6,NaN,NaN,0,NaN,210,Europe/London,2013-07-11,NaN
145,2633334,Ystradgynlais,Ystradgynlais,51.76667,-3.76667,P,PPLA3,GB,GB,WLS,Y8,00NN110,NaN,0,NaN,68,Europe/London,2011-07-31,NaN
146,2633335,Ystrad-ffin,Ystrad-ffin,52.10000,-3.76667,P,PPL,GB,GB,WLS,X7,NaN,NaN,0,NaN,399,Europe/London,2013-07-11,NaN
147,2633336,Ystradfellte,Ystradfellte,51.80897,-3.55299,P,PPL,GB,NaN,WLS,Y8,00NN109,NaN,0,NaN,252,Europe/London,2011-03-03,NaN
148,2633337,Ystalyfera,Ystalyfera,51.76716,-3.78082,P,PPL,GB,NaN,WLS,Y5,00NZ031,NaN,10218,NaN,74,Europe/London,2011-03-03,NaN
149,2633338,Yspytty-Ystwyth,Yspytty-Ystwyth,52.33333,-3.86667,P,PPL,GB,NaN,WLS,X6,NaN,NaN,0,NaN,165,Europe/London,2013-07-11,NaN
150,2633339,Ysbyty Ifan,Ysbyty Ifan,53.01667,-3.73333,P,PPL,GB,NaN,WLS,Y2,NaN,NaN,0,NaN,246,Europe/London,2013-12-06,NaN
151,2633340,Yspytty Cynfyn,Yspytty Cynfyn,52.40000,-3.83333,P,PPL,GB,GB,WLS,X6,NaN,NaN,0,NaN,212,Europe/London,2013-07-11,NaN
155,2633344,Yoxford,Yoxford,52.26819,1.50681,P,PPL,GB,NaN,ENG,N5,42UG,NaN,0,NaN,16,Europe/London,2011-03-03,NaN
156,2633345,Yoxall,Yoxall,52.76659,-1.79068,P,PPL,GB,NaN,ENG,M9,41UC,NaN,0,NaN,66,Europe/London,2011-03-03,NaN
157,2633346,Youlgreave,Youlgreave,53.17399,-1.69044,P,PPL,GB,NaN,ENG,D3,17UF,NaN,0,NaN,187,Europe/London,2010-11-07,NaN
158,2633347,Yorton,Yorton,52.80921,-2.73854,P,PPL,GB,NaN,ENG,L6,00GG130,NaN,0,NaN,87,Europe/London,2011-03-03,NaN
163,2633352,York,York,53.95763,-1.08271,P,PPLA2,GB,NaN,ENG,Q5,NaN,NaN,144202,NaN,17,Europe/London,2012-03-30,NaN
165,2633354,Yokefleet,Yokefleet,53.70805,-0.75738,P,PPL,GB,NaN,ENG,E1,00FB018,NaN,0,NaN,5,Europe/London,2011-03-03,NaN
166,2633355,Yockleton,Yockleton,52.68547,-2.88917,P,PPL,GB,NaN,ENG,L6,00GG187,NaN,0,NaN,98,Europe/London,2011-03-03,NaN
172,2633363,Yiewsley,Yiewsley,51.51326,-0.47297,P,PPL,GB,NaN,ENG,GLA,F9,NaN,0,NaN,33,Europe/London,2010-05-24,NaN
175,2633366,Yetminster,Yetminster,50.89579,-2.57959,P,PPL,GB,NaN,ENG,D6,19UH,NaN,0,NaN,62,Europe/London,2011-03-03,NaN
176,2633367,Yetlington,Yetlington,55.38190,-1.96856,P,PPL,GB,NaN,ENG,J6,00EM031,NaN,0,NaN,190,Europe/London,2011-03-03,NaN
179,2633370,Yerbeston,Yerbeston,51.74600,-4.80767,P,PPL,GB,NaN,WLS,Y7,00NS026,NaN,0,NaN,63,Europe/London,2011-03-03,NaN
180,2633371,Yeovilton,Yeovilton,51.00359,-2.64898,P,PPL,GB,NaN,ENG,M3,40UD,NaN,0,NaN,19,Europe/London,2011-03-03,NaN
182,2633373,Yeovil,Yeovil,50.94159,-2.63211,P,PPL,GB,NaN,ENG,M3,40UD,NaN,43733,NaN,55,Europe/London,2011-03-03,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51566,10377357,Upper Ley,Upper Ley,51.85693,-2.39635,P,PPL,GB,NaN,ENG,E6,23UD,23UD038,0,NaN,45,Europe/London,2015-07-18,NaN
51568,10377359,Grange Court,Grange Court,51.84797,-2.38841,P,PPL,GB,NaN,ENG,E6,23UD,23UD038,0,NaN,40,Europe/London,2015-07-18,NaN
51569,10377360,Northwood Green,Northwood Green,51.84445,-2.40918,P,PPL,GB,NaN,ENG,E6,23UD,23UD038,0,NaN,35,Europe/London,2015-07-18,NaN
51570,10377361,Taynton Village,Taynton Village,51.89395,-2.39549,P,PPL,GB,NaN,ENG,E6,23UD,23UD034,0,NaN,64,Europe/London,2015-07-18,NaN
51571,10377362,Mungoswells,Mungoswells,56.00088,-2.81108,P,PPL,GB,NaN,SCT,U6,NaN,NaN,0,NaN,34,Europe/London,2015-07-18,NaN
51572,10377363,Ballencrieff,Ballencrieff,55.99310,-2.82919,P,PPL,GB,NaN,SCT,U6,NaN,NaN,0,NaN,49,Europe/London,2015-07-18,NaN
51573,10377364,Spittal,Spittal,55.98468,-2.86786,P,PPL,GB,NaN,SCT,U6,NaN,NaN,0,NaN,38,Europe/London,2015-07-18,NaN
51576,10377368,Grasholme,Grasholme,54.58999,-2.11834,P,PPL,GB,NaN,ENG,D8,00EJ071,NaN,0,NaN,301,Europe/London,2015-07-19,NaN
51579,10377371,Edburton,Edburton,50.89047,-0.25466,P,PPL,GB,NaN,ENG,P6,45UF,45UF027,0,NaN,127,Europe/London,2015-07-19,NaN
51589,10377694,Soar,Soar,53.22302,-4.42011,P,PPL,GB,NaN,WLS,X1,00NA001,NaN,0,NaN,20,Europe/London,2015-07-19,NaN
51591,10377699,Bethel,Bethel,53.20781,-4.40406,P,PPL,GB,NaN,WLS,X1,00NA006,NaN,0,NaN,6,Europe/London,2015-07-19,NaN
51592,10377701,Trefdraeth,Trefdraeth,53.20542,-4.38951,P,PPL,GB,NaN,WLS,X1,00NA006,NaN,0,NaN,9,Europe/London,2015-07-19,NaN
51593,10377703,Malltraeth,Malltraeth,53.19243,-4.38509,P,PPL,GB,NaN,WLS,X1,00NA006,NaN,0,NaN,5,Europe/London,2015-07-19,NaN
51594,10377705,Hermon,Hermon,53.19269,-4.41045,P,PPL,GB,NaN,WLS,X1,00NA006,NaN,0,NaN,1,Europe/London,2015-07-19,NaN
51595,10377710,Paradwys,Paradwys,53.21200,-4.36505,P,PPL,GB,NaN,WLS,X1,00NA026,NaN,0,NaN,7,Europe/London,2015-07-19,NaN
51596,10377712,Capel Mawr,Capel Mawr,53.22009,-4.37578,P,PPL,GB,NaN,WLS,X1,00NA026,NaN,0,NaN,19,Europe/London,2015-07-19,NaN
51601,10377724,Broadridge Heath,Broadridge Heath,51.07223,-0.36019,P,PPL,GB,NaN,ENG,P6,45UF,45UF006,0,NaN,53,Europe/London,2015-07-19,NaN
51602,10377733,Strood Green,Strood Green,51.08328,-0.37731,P,PPL,GB,NaN,ENG,P6,45UF,45UF028,0,NaN,50,Europe/London,2015-07-19,NaN
51607,10377751,Clemsfold,Clemsfold,51.08953,-0.39512,P,PPL,GB,NaN,ENG,P6,45UF,45UF021,0,NaN,47,Europe/London,2015-07-19,NaN
51608,10377752,Rowhook,Rowhook,51.09554,-0.39783,P,PPL,GB,NaN,ENG,P6,45UF,45UF028,0,NaN,49,Europe/London,2015-07-19,NaN
51609,10377753,Ellen's Green,Ellen's Green,51.10861,-0.43302,P,PPL,GB,NaN,ENG,N7,43UL,43UL009,0,NaN,62,Europe/London,2015-07-19,NaN
51610,10377754,Rudwick,Rudwick,51.09608,-0.44589,P,PPL,GB,NaN,ENG,P6,45UF,45UF017,0,NaN,43,Europe/London,2015-07-19,NaN
51616,10377760,Hill Wootton,Hill Wootton,52.31716,-1.55946,P,PPL,GB,NaN,ENG,P3,44UF,44UF019,0,NaN,74,Europe/London,2015-07-19,NaN
51617,10377761,Guys Cliffe,Guys Cliffe,52.29638,-1.57675,P,PPL,GB,NaN,ENG,P3,44UF,44UF029,0,NaN,74,Europe/London,2015-07-19,NaN
51631,10377783,Ashley,Ashley,50.89229,-3.49773,P,PPL,GB,NaN,ENG,D4,18UD,18UD052,0,NaN,83,Europe/London,2015-07-19,NaN
51651,10377803,Little London,Little London,50.95751,0.23299,P,PPL,GB,NaN,ENG,E2,21UH,21UH020,0,NaN,76,Europe/London,2015-07-19,NaN
51657,10377809,Pedlinge,Pedlinge,51.07878,1.05301,P,PPL,GB,NaN,ENG,G5,NaN,29UL022,0,NaN,59,Europe/London,2015-07-19,NaN
51670,10377822,Abbeymead,Abbeymead,51.84893,-2.20040,P,PPL,GB,NaN,ENG,E6,23UE,NaN,0,NaN,69,Europe/London,2015-07-19,NaN
51712,10377869,The Coombes,The Coombes,50.33456,-4.52517,P,PPL,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,39,Europe/London,2015-07-20,NaN
51713,10377870,Killigarth,Killigarth,50.33990,-4.51276,P,PPL,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,45,Europe/London,2015-07-20,NaN

In [121]:
cols = df_alt.columns.tolist()

In [122]:
cols

['geoid',
 'name',
 'asciiname',
 'lat',
 'long',
 'feature_class',
 'feature_code',
 'country_code',
 'cc2',
 'adm1',
 'adm2',
 'adm3',
 'adm4',
 'pop',
 'elev',
 'delev',
 'timezone',
 'moddate',
 'parent']

In [123]:
cols = ['geoid',
 'name',
 'asciiname',
 'lat',
 'long',
 'feature_class',
 'feature_code',
 'country_code',
 'cc2',
 'adm1',
 'adm2',
 'adm3',
 'adm4',
 'pop',
 'elev',
 'delev',
 'timezone',
 'moddate',
 ]

In [127]:
cols = ['geoid',
 'name',
 'parent',       
 'asciiname',
 'lat',
 'long',
 'feature_class',
 'feature_code',
 'country_code',
 'cc2',
 'adm1',
 'adm2',
 'adm3',
 'adm4',
 'pop',
 'elev',
 'delev',
 'timezone',
 'moddate',
 ]

In [128]:
df_alt = df_alt[cols]

In [129]:
df_alt

,geoid,name,parent,asciiname,lat,long,feature_class,feature_code,country_code,cc2,adm1,adm2,adm3,adm4,pop,elev,delev,timezone,moddate
102,145972,Xylophaghou,NaN,Xylophaghou,34.97917,33.85000,P,PPL,GB,NaN,NaN,NaN,NaN,NaN,0,NaN,51,Asia/Nicosia,2014-05-29
104,146033,Trachóni,NaN,Trachoni,34.65756,32.96534,P,PPL,GB,NaN,NaN,NaN,NaN,NaN,0,NaN,30,Asia/Nicosia,2014-03-05
135,2633324,Zennor,NaN,Zennor,50.19057,-5.56614,P,PPL,GB,NaN,ENG,C6,00HE213,NaN,0,NaN,109,Europe/London,2011-03-03
136,2633325,Zelah,NaN,Zelah,50.32332,-5.07897,P,PPL,GB,NaN,ENG,C6,00HE129,NaN,0,NaN,76,Europe/London,2011-03-03
137,2633326,Zeals,NaN,Zeals,51.08558,-2.31230,P,PPL,GB,NaN,ENG,P8,00HY259,NaN,0,NaN,145,Europe/London,2011-03-03
138,2633327,Zeal Monachorum,NaN,Zeal Monachorum,50.82117,-3.81898,P,PPL,GB,NaN,ENG,D4,18UD,NaN,0,NaN,136,Europe/London,2011-03-03
139,2633328,Ythsie,NaN,Ythsie,57.36667,-2.18333,P,PPL,GB,NaN,SCT,T6,NaN,NaN,0,NaN,49,Europe/London,2004-10-06
142,2633331,Ystradowen,NaN,Ystradowen,51.49056,-3.42194,P,PPL,GB,NaN,WLS,Z3,NaN,NaN,0,NaN,67,Europe/London,2012-01-17
143,2633332,Ystrad Mynach,NaN,Ystrad Mynach,51.64276,-3.23620,P,PPLA2,GB,NaN,WLS,X4,00PK012,NaN,0,NaN,115,Europe/London,2011-03-03
144,2633333,Ystrad-Meurig,NaN,Ystrad-Meurig,52.28333,-3.91667,P,PPL,GB,GB,WLS,X6,NaN,NaN,0,NaN,210,Europe/London,2013-07-11
145,2633334,Ystradgynlais,NaN,Ystradgynlais,51.76667,-3.76667,P,PPLA3,GB,GB,WLS,Y8,00NN110,NaN,0,NaN,68,Europe/London,2011-07-31
146,2633335,Ystrad-ffin,NaN,Ystrad-ffin,52.10000,-3.76667,P,PPL,GB,GB,WLS,X7,NaN,NaN,0,NaN,399,Europe/London,2013-07-11
147,2633336,Ystradfellte,NaN,Ystradfellte,51.80897,-3.55299,P,PPL,GB,NaN,WLS,Y8,00NN109,NaN,0,NaN,252,Europe/London,2011-03-03
148,2633337,Ystalyfera,NaN,Ystalyfera,51.76716,-3.78082,P,PPL,GB,NaN,WLS,Y5,00NZ031,NaN,10218,NaN,74,Europe/London,2011-03-03
149,2633338,Yspytty-Ystwyth,NaN,Yspytty-Ystwyth,52.33333,-3.86667,P,PPL,GB,NaN,WLS,X6,NaN,NaN,0,NaN,165,Europe/London,2013-07-11
150,2633339,Ysbyty Ifan,NaN,Ysbyty Ifan,53.01667,-3.73333,P,PPL,GB,NaN,WLS,Y2,NaN,NaN,0,NaN,246,Europe/London,2013-12-06
151,2633340,Yspytty Cynfyn,NaN,Yspytty Cynfyn,52.40000,-3.83333,P,PPL,GB,GB,WLS,X6,NaN,NaN,0,NaN,212,Europe/London,2013-07-11
155,2633344,Yoxford,NaN,Yoxford,52.26819,1.50681,P,PPL,GB,NaN,ENG,N5,42UG,NaN,0,NaN,16,Europe/London,2011-03-03
156,2633345,Yoxall,NaN,Yoxall,52.76659,-1.79068,P,PPL,GB,NaN,ENG,M9,41UC,NaN,0,NaN,66,Europe/London,2011-03-03
157,2633346,Youlgreave,NaN,Youlgreave,53.17399,-1.69044,P,PPL,GB,NaN,ENG,D3,17UF,NaN,0,NaN,187,Europe/London,2010-11-07
158,2633347,Yorton,NaN,Yorton,52.80921,-2.73854,P,PPL,GB,NaN,ENG,L6,00GG130,NaN,0,NaN,87,Europe/London,2011-03-03
163,2633352,York,NaN,York,53.95763,-1.08271,P,PPLA2,GB,NaN,ENG,Q5,NaN,NaN,144202,NaN,17,Europe/London,2012-03-30
165,2633354,Yokefleet,NaN,Yokefleet,53.70805,-0.75738,P,PPL,GB,NaN,ENG,E1,00FB018,NaN,0,NaN,5,Europe/London,2011-03-03
166,2633355,Yockleton,NaN,Yockleton,52.68547,-2.88917,P,PPL,GB,NaN,ENG,L6,00GG187,NaN,0,NaN,98,Europe/London,2011-03-03
172,2633363,Yiewsley,NaN,Yiewsley,51.51326,-0.47297,P,PPL,GB,NaN,ENG,GLA,F9,NaN,0,NaN,33,Europe/London,2010-05-24
175,2633366,Yetminster,NaN,Yetminster,50.89579,-2.57959,P,PPL,GB,NaN,ENG,D6,19UH,NaN,0,NaN,62,Europe/London,2011-03-03
176,2633367,Yetlington,NaN,Yetlington,55.38190,-1.96856,P,PPL,GB,NaN,ENG,J6,00EM031,NaN,0,NaN,190,Europe/London,2011-03-03
179,2633370,Yerbeston,NaN,Yerbeston,51.74600,-4.80767,P,PPL,GB,NaN,WLS,Y7,00NS026,NaN,0,NaN,63,Europe/London,2011-03-03
180,2633371,Yeovilton,NaN,Yeovilton,51.00359,-2.64898,P,PPL,GB,NaN,ENG,M3,40UD,NaN,0,NaN,19,Europe/London,2011-03-03
182,2633373,Yeovil,NaN,Yeovil,50.94159,-2.63211,P,PPL,GB,NaN,ENG,M3,40UD,NaN,43733,NaN,55,Europe/London,2011-03-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51566,10377357,Upper Ley,NaN,Upper Ley,51.85693,-2.39635,P,PPL,GB,NaN,ENG,E6,23UD,23UD038,0,NaN,45,Europe/London,2015-07-18
51568,10377359,Grange Court,NaN,Grange Court,51.84797,-2.38841,P,PPL,GB,NaN,ENG,E6,23UD,23UD038,0,NaN,40,Europe/London,2015-07-18
51569,10377360,Northwood Green,NaN,Northwood Green,51.84445,-2.40918,P,PPL,GB,NaN,ENG,E6,23UD,23UD038,0,NaN,35,Europe/London,2015-07-18
51570,10377361,Taynton Village,NaN,Taynton Village,51.89395,-2.39549,P,PPL,GB,NaN,ENG,E6,23UD,23UD034,0,NaN,64,Europe/London,2015-07-18
51571,10377362,Mungoswells,NaN,Mungoswells,56.00088,-2.81108,P,PPL,GB,NaN,SCT,U6,NaN,NaN,0,NaN,34,Europe/London,2015-07-18
51572,10377363,Ballencrieff,NaN,Ballencrieff,55.99310,-2.82919,P,PPL,GB,NaN,SCT,U6,NaN,NaN,0,NaN,49,Europe/London,2015-07-18
51573,10377364,Spittal,NaN,Spittal,55.98468,-2.86786,P,PPL,GB,NaN,SCT,U6,NaN,NaN,0,NaN,38,Europe/London,2015-07-18
51576,10377368,Grasholme,NaN,Grasholme,54.58999,-2.11834,P,PPL,GB,NaN,ENG,D8,00EJ071,NaN,0,NaN,301,Europe/London,2015-07-19
51579,10377371,Edburton,NaN,Edburton,50.89047,-0.25466,P,PPL,GB,NaN,ENG,P6,45UF,45UF027,0,NaN,127,Europe/London,2015-07-19
51589,10377694,Soar,NaN,Soar,53.22302,-4.42011,P,PPL,GB,NaN,WLS,X1,00NA001,NaN,0,NaN,20,Europe/London,2015-07-19
51591,10377699,Bethel,NaN,Bethel,53.20781,-4.40406,P,PPL,GB,NaN,WLS,X1,00NA006,NaN,0,NaN,6,Europe/London,2015-07-19
51592,10377701,Trefdraeth,NaN,Trefdraeth,53.20542,-4.38951,P,PPL,GB,NaN,WLS,X1,00NA006,NaN,0,NaN,9,Europe/London,2015-07-19
51593,10377703,Malltraeth,NaN,Malltraeth,53.19243,-4.38509,P,PPL,GB,NaN,WLS,X1,00NA006,NaN,0,NaN,5,Europe/London,2015-07-19
51594,10377705,Hermon,NaN,Hermon,53.19269,-4.41045,P,PPL,GB,NaN,WLS,X1,00NA006,NaN,0,NaN,1,Europe/London,2015-07-19
51595,10377710,Paradwys,NaN,Paradwys,53.21200,-4.36505,P,PPL,GB,NaN,WLS,X1,00NA026,NaN,0,NaN,7,Europe/London,2015-07-19
51596,10377712,Capel Mawr,NaN,Capel Mawr,53.22009,-4.37578,P,PPL,GB,NaN,WLS,X1,00NA026,NaN,0,NaN,19,Europe/London,2015-07-19
51601,10377724,Broadridge Heath,NaN,Broadridge Heath,51.07223,-0.36019,P,PPL,GB,NaN,ENG,P6,45UF,45UF006,0,NaN,53,Europe/London,2015-07-19
51602,10377733,Strood Green,NaN,Strood Green,51.08328,-0.37731,P,PPL,GB,NaN,ENG,P6,45UF,45UF028,0,NaN,50,Europe/London,2015-07-19
51607,10377751,Clemsfold,NaN,Clemsfold,51.08953,-0.39512,P,PPL,GB,NaN,ENG,P6,45UF,45UF021,0,NaN,47,Europe/London,2015-07-19
51608,10377752,Rowhook,NaN,Rowhook,51.09554,-0.39783,P,PPL,GB,NaN,ENG,P6,45UF,45UF028,0,NaN,49,Europe/London,2015-07-19
51609,10377753,Ellen's Green,NaN,Ellen's Green,51.10861,-0.43302,P,PPL,GB,NaN,ENG,N7,43UL,43UL009,0,NaN,62,Europe/London,2015-07-19
51610,10377754,Rudwick,NaN,Rudwick,51.09608,-0.44589,P,PPL,GB,NaN,ENG,P6,45UF,45UF017,0,NaN,43,Europe/London,2015-07-19
51616,10377760,Hill Wootton,NaN,Hill Wootton,52.31716,-1.55946,P,PPL,GB,NaN,ENG,P3,44UF,44UF019,0,NaN,74,Europe/London,2015-07-19
51617,10377761,Guys Cliffe,NaN,Guys Cliffe,52.29638,-1.57675,P,PPL,GB,NaN,ENG,P3,44UF,44UF029,0,NaN,74,Europe/London,2015-07-19
51631,10377783,Ashley,NaN,Ashley,50.89229,-3.49773,P,PPL,GB,NaN,ENG,D4,18UD,18UD052,0,NaN,83,Europe/London,2015-07-19
51651,10377803,Little London,NaN,Little London,50.95751,0.23299,P,PPL,GB,NaN,ENG,E2,21UH,21UH020,0,NaN,76,Europe/London,2015-07-19
51657,10377809,Pedlinge,NaN,Pedlinge,51.07878,1.05301,P,PPL,GB,NaN,ENG,G5,NaN,29UL022,0,NaN,59,Europe/London,2015-07-19
51670,10377822,Abbeymead,NaN,Abbeymead,51.84893,-2.20040,P,PPL,GB,NaN,ENG,E6,23UE,NaN,0,NaN,69,Europe/London,2015-07-19
51712,10377869,The Coombes,NaN,The Coombes,50.33456,-4.52517,P,PPL,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,39,Europe/London,2015-07-20
51713,10377870,Killigarth,NaN,Killigarth,50.33990,-4.51276,P,PPL,GB,NaN,ENG,C6,00HE065,NaN,0,NaN,45,Europe/London,2015-07-20

In [132]:
for index, row in ds.iterrows():
    for a_name in row['ls_altname']:
         a_name = df_alt.ix('name',)

SyntaxError: can't assign to function call (<ipython-input-132-1f29eea0be35>, line 3)